### ISSUE TITLE
Wrong timestamps sent to flapjack

### ISSUE THREAD

**Issue by Nesousx** [f0o/glowing-tyrion#5]
Hi f0o,

I know, it is an old "branch", but I am trying to get in touch with you, because I heard you were the one who wrote the nagios-receiver alert transport, and I have an issue with it.

I tried to open an issue on LibreNMS but it was closed because it is not related to adding a new device.

However, I sincerely believe there is a real issue and people might benefit from a fix.

Please find below my original message posted on the LibreNMS' Github.

Many thanks in advance,

-------

I've been trying to set up a nagios receiver alert transport in order to send LibreNMS alerts to Flapjack. However, I couldn't do it.

It seems that flapjack expects to receive the timestamp format in the UNIX format:

> The line must: - split into at least 9 tab-separated words - contain a unix timestamp in the 2nd word (seconds since epoch) - so just a whole number - the first word (object type) must contain either [HOSTPERFDATA] or [SERVICEPERFDATA].

Source: http://flapjack.io/docs/1.0/usage/Configuring-Nagios/

Currently, LIbreNMS sends a timestamp like below:
`2018-08-31 10:40:44`

According to my research, the file responsible for this is:

`LibreNMS/Alert/Transport/Nagios.php`

and does something like this:

```
    {
        /*
         host_perfdata_file_template=
         [HOSTPERFDATA]\t
         $TIMET$\t
         $HOSTNAME$\t
         HOST\t
         $HOSTSTATE$\t
         $HOSTEXECUTIONTIME$\t
         $HOSTLATENCY$\t
         $HOSTOUTPUT$\t
         $HOSTPERFDATA$
         */

        $format = '';
        $format .= "[HOSTPERFDATA]\t";
        $format .= $obj['timestamp'] . "\t";
        $format .= $obj['hostname'] . "\t";
        $format .= md5($obj['rule']) . "\t"; //FIXME: Better entity
        $format .= ($obj['state'] ? $obj['severity'] : "ok") . "\t";
        $format .= "0\t";
        $format .= "0\t";
        $format .= str_replace("\n", "", nl2br($obj['msg'])) . "\t";
        $format .= "NULL"; //FIXME: What's the HOSTPERFDATA equivalent for LibreNMS? Oo
        $format .= "\n";
        return file_put_contents($opts, $format);
    }
```

Now, I understand that the timestamp comes from the variable `$obj['timestamp']`. However, I have no idea how to modify it. Moreover, I have the feeling that modifying the variable system wide could turn all the timestamps (like for email alerts) to the new Unix format (which is not really human readable).

EDIT: manually sending the line to the named pipe while only replacing "librenms timestamp" by a Unix's one perfectly works.

Would that be possible (and clean?) to edit the nagios.php file so that it converts the already existing timestamp to the UNIX one? Or anything more clever... I am not a developer at all.. and I think I identified and issue, but my solution might not be the good one.

Thanks in advance, and thanks for the great product. :)

**Comment by f0o** [comment]
Sorry this was lost in loads of spam so I just got through all the notifications in the actual github website.

That variable is populated by the SQL Database, you could use php's date formatting function to convert it back into unixtimestamps if you want..

But I think this is now obsolete since we moved away from the old alerting model and onto Laravel stuff.

Sorry again for the late and probably obsolete answer :/

**Comment by Nesousx** [comment]
Hi,

No problem. I did push a small "fix" to librenms that did the trick for me, and hopefully maybe someone else. :)

**Comment by f0o** [comment]
Awesome glad to hear!

Open Source is a community effort after all :)

Mind if I close this ticket?

**Comment by Nesousx** [comment]
Not at all. You can close it. 

Indeed open source is awesome. :)
